language: java

jdk:
  - oraclejdk8

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq twm

before_script:
  - Xvfb :5 -screen 0 1280x1024x24 &
#  - twm -display :5 -v &
  - export DISPLAY=:5.0

